name: lifemd_mobile_custom_lint_test_examples
description: A custom lint test examples lifemd_patient_portal_mobile.

environment:
  sdk: '>=3.1.3 <4.0.0'

dev_dependencies:
  custom_lint: ^0.5.7
  fake_async: ^1.3.1
  lifemd_mobile_custom_lint:
    path: ../
  flutter_test: # unit tests
    sdk: flutter

