name: lifemd_mobile_custom_lint
description: A custom lint rules for lifemd_patient_portal_mobile.

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  # we will use an analyzer for inspecting Dart files
  analyzer: ^5.7.0 # unable to update because of `custom_lint_builder`
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.0
  meta: ^1.7.0
