name: lifemd_mobile_custom_lint
description: A custom lint rules for lifemd_patient_portal_mobile.

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  # we will use an analyzer for inspecting Dart files
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.7
  meta: ^1.9.1
  quiver: ^3.2.1
